# Generated by Django 3.0.5 on 2020-04-30 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False, max_length=10)),
                ('time', models.DateTimeField(verbose_name='time published')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.User')),
            ],
        ),
    ]
